---
title: "Wk4Homework"
output: html_document
date: "2023-10-25"
---

Setup of Libraries and Download of Files
```{r setup, include=FALSE}

library(sf)
library(tidyverse)
library(here)
library(countrycode)

#Load in country borders
country_borders <- st_read(here("hw4_data","World_Countries_Generalized","World_Countries_Generalized.shp"))

#Load in gender inequality data
#Note - Metadata indicates that the Gender Inequality Index is abbreviated 'GII', distinct from the Gender Development Index (GDI)
hdr_indices <- read_csv(here("hw4_data", "hdr_composite.csv"))

```

Data Management
```{r}

#Filter hdr data to relevant columns only
hdr_light <- hdr_indices %>%
  select("iso3","gii_2010", "gii_2021")

#Create new column of difference in inequality
#Note - Higher values of GII denote higher degrees of inequality. Therefore, negative values in the difference column imply improvements to gender inequality in corresponding countries
hdr_diff <- hdr_light %>%
  mutate(., "gii_diff" = gii_2021 - gii_2010)

#Add new column to country_borders corresponding to iso3c (convert from iso2c)
#I will use the ISO column over AFF_ISO because I only want to include sovereign states and not overseas territories like Aruba or American Samoa
country_borders <- country_borders %>%
  mutate(., "iso3" = countrycode(country_borders$ISO, origin = 'iso2c', destination = 'iso3c'))

```

Join Datasets
```{r}

#Left join - country borders 'onto' hdr data
#I won't drop NAs just yet because I want to allow the mapmaker to handle those cases as they please
gii_spatial <- hdr_diff %>%
  left_join(., country_borders)

```



